# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

# 1. 这里改成你的博客标题
title = "_sun_empty's Blog"

# 2. 【核心】这里必须改成你的 GitHub Pages 根地址，注意最后要有斜杠 /
baseURL = "https://sun1028sun.github.io/"

# theme = "FixIt"

# 3. 这里改成中文，界面就会显示中文了
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"

hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ...下面的 ignoreLogs 保持不变...
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]
